In [13]:
import torch
import numpy as np
import random

#根据已有数据创建张量
def test01():

    data = torch.tensor(10)    #创建标量
    print(data)

    #创建指定形状张量
    data = np.random.randn(2, 3)   #numpy创建张量
    data = torch.tensor(data)
    print(data)

    #使用list
    data = [[10., 20., 30.], [40., 50., 60.]]
    torch.tensor(data)
    print(data)

#创建指定形状张量
def test02():

    #创建两行三列张量
    data = torch.Tensor(2, 3)
    print(data)

    #创建指定值张量
    data = torch.Tensor([2, 3])    #传递列表
    print(data)

#创建指定类型
def test03():

    #前面都是默认类型
    #创建一个 int 类型的张量
    data = torch.IntTensor(2, 3)
    print(data)

    # torch.ShortTensor(2, 3)    #创建一个 int16 的张量
    # torch.LongTensor(2, 3)    #创建一个 int32 的张量
    # torch.FloatTensor(2, 3)    #float32


    

if __name__ == '__main__':
    test03()
    
    

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[ 8176, 15808,   716],
        [    0,     0,     0]], dtype=torch.int16)
tensor([[0, 0, 0],
        [0, 0, 0]])
